---
- name: install and config docker
  hosts: docker
  become: true
  become_user: root
  tasks:
    - package:
        name: "{{ item }}"
        state: present
      with_items:
        - polkit
        - docker

    - service:
        name: "{{ item }}"
        state: started
        enabled: true
      with_items:
        - polkit
        - docker
...
