---
- name: install and config docker
  hosts: docker
  become: true
  become_user: root
  tasks:
    - name: start services
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      with_items:
        - polkit
        - docker
    - name: add vagrant user to docker group
      user:
        name: vagrant
        groups: docker
        append: yes
...
